name: Update API Docs

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'docs/swagger/swagger.yaml'  # Only trigger when the OpenAPI spec changes
  release:
    types: [published]  # Trigger when a new release is published
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API Repository
        uses: actions/checkout@v3

      - name: Create target directory if needed
        run: |
          mkdir -p temp_dir
          cp docs/swagger/swagger.yaml temp_dir/
          
      # Option 1: Using an action specifically designed for this purpose
      - name: Push to Docs Repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_REPO_PAT }}
        with:
          source_file: 'docs/swagger/swagger.yaml'
          destination_repo: 'scarlett-foundation/docs'
          destination_folder: 'api'  # Adjust to your docs repo structure
          user_email: 'api-bot@scarlett.ai'  # Use a bot email
          user_name: 'Scarlett API Bot'
          commit_message: 'Update API specification from API repo' 